add docker commands to bashly - start

diff --git a/cli b/cli
--- a/cli
+++ b/cli
@@ -26,8 +26,8 @@ cli_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   Compose Commands\n" "compose "
   printf "  %s   Download a file\n" "download"
-  printf "  %s   Upload a file\n" "upload  "
   echo
 
   # :command.long_usage
@@ -47,7 +47,99 @@ cli_usage() {
 
     # :environment_variable.usage
     printf "  %s\n" "API_KEY"
-    printf "    Set your API key\n"
+    printf "\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_compose_usage() {
+  printf "cli compose - Compose Commands\n\n"
+  printf "Alias: dc*\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  cli compose COMMAND\n"
+  printf "  cli compose [COMMAND] --help | -h\n"
+  echo
+  # :command.usage_commands
+  printf "%s\n" "Commands:"
+  printf "  %s   Run Docker Compose\n" "start  "
+  printf "  %s   Stop all services\n" "stop   "
+  printf "  %s   Rebuild all services\n" "rebuild"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_compose_start_usage() {
+  printf "cli compose start - Run Docker Compose\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  cli compose start\n"
+  printf "  cli compose start --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_compose_stop_usage() {
+  printf "cli compose stop - Stop all services\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  cli compose stop\n"
+  printf "  cli compose stop --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+cli_compose_rebuild_usage() {
+  printf "cli compose rebuild - Rebuild all services\n\n"
+
+  printf "%s\n" "Usage:"
+  printf "  cli compose rebuild [--] [...]\n"
+  printf "  cli compose rebuild --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n "$long_usage" ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -109,48 +201,6 @@ cli_download_usage() {
   fi
 }
 
-# :command.usage
-cli_upload_usage() {
-  printf "cli upload - Upload a file\n\n"
-  printf "Alias: u\n"
-  echo
-
-  printf "%s\n" "Usage:"
-  printf "  cli upload SOURCE [OPTIONS]\n"
-  printf "  cli upload --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n "$long_usage" ]]; then
-    printf "%s\n" "Options:"
-
-    # :command.usage_flags
-    # :flag.usage
-    printf "  %s\n" "--user, -u USER (required)"
-    printf "\n"
-    echo
-
-    # :flag.usage
-    printf "  %s\n" "--password, -p PASSWORD"
-    printf "\n"
-    echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
-    # :command.usage_args
-    printf "%s\n" "Arguments:"
-
-    # :argument.usage
-    printf "  %s\n" "SOURCE"
-    printf "    File to upload\n"
-    echo
-
-  fi
-}
-
 # :command.normalize_input
 # :command.normalize_input_function
 normalize_input() {
@@ -195,6 +245,15 @@ inspect_args() {
     echo args: none
   fi
 
+  if ((${#other_args[@]})); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
+
   if ((${#deps[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
@@ -222,12 +281,48 @@ debug() {
   fi
 }
 
-# bin/lib/sample_function.sh
-sample_function() {
-  echo "it works"
+# :command.command_functions
+
+# :command.function
+cli_compose_start_command() {
+
+  # bin/compose_start_command.sh
+  echo "# This file is located at 'bin/compose_start_command.sh'."
+  echo "# It contains the implementation for the 'cli compose start' command."
+  echo "# The code you write here will be wrapped by a function named 'cli_compose_start_command()'."
+  echo "# Feel free to edit this file; your changes will persist when regenerating."
+  inspect_args
+
 }
 
-# :command.command_functions
+# :command.function
+cli_compose_stop_command() {
+
+  # bin/compose_stop_command.sh
+  echo "# This file is located at 'bin/compose_stop_command.sh'."
+  echo "# It contains the implementation for the 'cli compose stop' command."
+  echo "# The code you write here will be wrapped by a function named 'cli_compose_stop_command()'."
+  echo "# Feel free to edit this file; your changes will persist when regenerating."
+  inspect_args
+
+}
+
+# :command.function
+cli_compose_rebuild_command() {
+
+  # bin/compose_rebuild_command.sh
+  inspect_args
+
+  # docker compose down && docker compose up "$@"
+
+  all=${other_args[*]}
+
+  # echo "$all"
+
+  docker compose down && docker compose up "$all"
+
+}
+
 # :command.function
 cli_download_command() {
 
@@ -241,29 +336,13 @@ cli_download_command() {
   source_url=${args[source]}
   force=${args[--force]}
 
-  echo $force
-
   if [[ $force ]]; then
     echo "downloading $source_url with --force"
   else
     echo "downloading $source_url"
   fi
 
-  debug 'hello'
-
-}
-
-# :command.function
-cli_upload_command() {
-
-  # bin/upload_command.sh
-  echo "# This file is located at 'bin/upload_command.sh'."
-  echo "# It contains the implementation for the 'cli upload' command."
-  echo "# The code you write here will be wrapped by a function named 'cli_upload_command()'."
-  echo "# Feel free to edit this file; your changes will persist when regenerating."
-  inspect_args
-
-  sample_function
+  debug hello world
 
 }
 
@@ -301,17 +380,17 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    compose | dc*)
+      action="compose"
+      shift
+      cli_compose_parse_requirements "$@"
+      shift $#
+      ;;
+
     download | d)
       action="download"
       shift
       cli_download_parse_requirements "$@"
-      shift $#
-      ;;
-
-    upload | u)
-      action="upload"
-      shift
-      cli_upload_parse_requirements "$@"
       shift $#
       ;;
 
@@ -343,6 +422,229 @@ parse_requirements() {
         # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+cli_compose_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        cli_compose_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action=${1:-}
+
+  case $action in
+    -*) ;;
+
+    start)
+      action="start"
+      shift
+      cli_compose_start_parse_requirements "$@"
+      shift $#
+      ;;
+
+    stop)
+      action="stop"
+      shift
+      cli_compose_stop_parse_requirements "$@"
+      shift $#
+      ;;
+
+    rebuild)
+      action="rebuild"
+      shift
+      cli_compose_rebuild_parse_requirements "$@"
+      shift $#
+      ;;
+
+    # :command.command_fallback
+    "")
+      cli_compose_usage >&2
+      exit 1
+      ;;
+
+    *)
+      printf "invalid command: %s\n" "$action" >&2
+      exit 1
+      ;;
+
+  esac
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+cli_compose_start_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        cli_compose_start_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="compose start"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+cli_compose_stop_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        cli_compose_stop_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="compose stop"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+cli_compose_rebuild_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      --help | -h)
+        long_usage=yes
+        cli_compose_rebuild_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="compose rebuild"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      --)
+        shift
+        other_args+=("$@")
+        break
+        ;;
+
+      -?*)
+        other_args+=("$1")
+        shift
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_catch_all
+        other_args+=("$1")
+        shift
 
         ;;
 
@@ -424,97 +726,6 @@ cli_download_parse_requirements() {
 
 }
 
-# :command.parse_requirements
-cli_upload_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-      --help | -h)
-        long_usage=yes
-        cli_upload_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="upload"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-      # :flag.case
-      --user | -u)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--user']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--user requires an argument: --user, -u USER" >&2
-          exit 1
-        fi
-        ;;
-
-      # :flag.case
-      --password | -p)
-
-        # :flag.case_arg
-        if [[ -n ${2+x} ]]; then
-          args['--password']="$2"
-          shift
-          shift
-        else
-          printf "%s\n" "--password requires an argument: --password, -p PASSWORD" >&2
-          exit 1
-        fi
-        ;;
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        # :argument.case
-        if [[ -z ${args['source']+x} ]]; then
-          args['source']=$1
-          shift
-        else
-          printf "invalid argument: %s\n" "$key" >&2
-          exit 1
-        fi
-
-        ;;
-
-    esac
-  done
-
-  # :command.required_args_filter
-  if [[ -z ${args['source']+x} ]]; then
-    printf "missing required argument: SOURCE\nusage: cli upload SOURCE [OPTIONS]\n" >&2
-
-    exit 1
-  fi
-
-  # :command.required_flags_filter
-  if [[ -z ${args['--user']+x} ]]; then
-    printf "missing required flag: --user, -u USER\n" >&2
-    exit 1
-  fi
-
-}
-
 # :command.initialize
 initialize() {
   declare -g version="0.1.0"
@@ -527,6 +738,7 @@ run() {
   # :command.globals
   declare -g long_usage=''
   declare -g -A args=()
+  declare -g -a other_args=()
   declare -g -A deps=()
   declare -g -a env_var_names=()
   declare -g -a input=()
@@ -535,8 +747,11 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "compose") cli_compose_command ;;
+    "compose start") cli_compose_start_command ;;
+    "compose stop") cli_compose_stop_command ;;
+    "compose rebuild") cli_compose_rebuild_command ;;
     "download") cli_download_command ;;
-    "upload") cli_upload_command ;;
   esac
 }
 
